services:
  vibe:
    build: .
    container_name: vibe-kanban
    user: "${LOCAL_UID:-0}:${LOCAL_GID:-0}"
    environment:
      - PORT=8085
      - HOST=0.0.0.0
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-Your Name}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-you@example.com}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-Your Name}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-you@example.com}
      # Optional: provide tokens via .env instead of interactive login
      # - GH_TOKEN=${GH_TOKEN}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ${HOME}/.codex:/home/node/.codex
      - ${HOME}/.config/gh:/home/node/.config/gh
      - ${HOME}/.ssh:/home/node/.ssh:ro
      - ${HOME}/.gitconfig:/home/node/.gitconfig:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/vibe:/home/node/.local/share/vibe-kanban
      - ./data/cache:/home/node/.cache/utils
      - ./data/worktrees:/var/tmp/vibe-kanban
      - ./data/work:/work
    ports:
      - "8085:8085"
    tty: true
    stdin_open: true
    restart: unless-stopped
